### ISSUE TITLE
Initial Planning

### ISSUE THREAD

**Issue by gmanuelTFS** [gmanuelTFS/VGP141#20]
PLAN
Convert our queue
Build units of different types
Queue up units to be built
Each unit should have a build time
Units of different types should have different build times
User interface to queue up the building of the units
Some type of visual to represent the build progress
When a unit is build, it should appear in the game world

EVENTUALLY
Tech tree
Build menu updates based on built buildings
Buildings appear automatically in the world
Units spawn at their appropriate building

**Comment by adelear** [comment]
No

**Comment by gmanuelTFS** [comment]
Yes

**Comment by RuniteOre** [comment]
:(
